namespace FetchGame;

enum ServerControl : byte {
    IDLE,
    OPENCAMERA,
    STARTTHREAD,
    STARTRECORDING,
    STOPRECORDING,
    QUIT,
    TESTFOCUS,
    SETFOCUS,
    STARTSTREAM,
    SETIRIS
}

enum SignalType: byte {
    ClientBringup,
    ClientStateUpdate,
    INDIGO,
    INDIGO_TRIAL_TRIGGER,
    CalibrationNextPose,
    CalibrationPoseReached,
    CalibrationDone
}

enum ManagerState: byte {
    IDLE,
    CONNECT,
    CONNECTED,
    OPENCAMERA,
    CAMERAOPENED,
    ERROR,
    STARTCAMTHREAD,
    THREADREADY,
    RECORDSTOPPED,
    WAITTHREAD,
    WAITSTART,
    WAITSTOP
}

table bring_up_message {
    server_name:string;
    num_cameras:short;
}

table Server {
    signal_type:SignalType = ClientBringup;
    control:ServerControl = IDLE;
    server_mesg:bring_up_message;
    config_folder:string;
    record_folder:string;
    encoder_setup:string;
    ptp_global_time:ulong;
    server_state:ManagerState = IDLE;
    focus_value:int;
    camera_serial:string;
    iris_value:int;
}

root_type Server;