// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FETCH_FETCHGAME_H_
#define FLATBUFFERS_GENERATED_FETCH_FETCHGAME_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace FetchGame {

struct bring_up_message;
struct bring_up_messageBuilder;

struct Server;
struct ServerBuilder;

enum ServerControl : int8_t {
  ServerControl_IDLE = 0,
  ServerControl_OPENCAMERA = 1,
  ServerControl_STARTTHREAD = 2,
  ServerControl_STARTRECORDING = 3,
  ServerControl_STOPRECORDING = 4,
  ServerControl_QUIT = 5,
  ServerControl_TESTFOCUS = 6,
  ServerControl_SETFOCUS = 7,
  ServerControl_STARTSTREAM = 8,
  ServerControl_SETIRIS = 9,
  ServerControl_MIN = ServerControl_IDLE,
  ServerControl_MAX = ServerControl_SETIRIS
};

inline const ServerControl (&EnumValuesServerControl())[10] {
  static const ServerControl values[] = {
    ServerControl_IDLE,
    ServerControl_OPENCAMERA,
    ServerControl_STARTTHREAD,
    ServerControl_STARTRECORDING,
    ServerControl_STOPRECORDING,
    ServerControl_QUIT,
    ServerControl_TESTFOCUS,
    ServerControl_SETFOCUS,
    ServerControl_STARTSTREAM,
    ServerControl_SETIRIS
  };
  return values;
}

inline const char * const *EnumNamesServerControl() {
  static const char * const names[11] = {
    "IDLE",
    "OPENCAMERA",
    "STARTTHREAD",
    "STARTRECORDING",
    "STOPRECORDING",
    "QUIT",
    "TESTFOCUS",
    "SETFOCUS",
    "STARTSTREAM",
    "SETIRIS",
    nullptr
  };
  return names;
}

inline const char *EnumNameServerControl(ServerControl e) {
  if (::flatbuffers::IsOutRange(e, ServerControl_IDLE, ServerControl_SETIRIS)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesServerControl()[index];
}

enum SignalType : int8_t {
  SignalType_ClientBringup = 0,
  SignalType_ClientStateUpdate = 1,
  SignalType_INDIGO = 2,
  SignalType_INDIGO_TRIAL_TRIGGER = 3,
  SignalType_CalibrationNextPose = 4,
  SignalType_CalibrationPoseReached = 5,
  SignalType_CalibrationDone = 6,
  SignalType_MIN = SignalType_ClientBringup,
  SignalType_MAX = SignalType_CalibrationDone
};

inline const SignalType (&EnumValuesSignalType())[7] {
  static const SignalType values[] = {
    SignalType_ClientBringup,
    SignalType_ClientStateUpdate,
    SignalType_INDIGO,
    SignalType_INDIGO_TRIAL_TRIGGER,
    SignalType_CalibrationNextPose,
    SignalType_CalibrationPoseReached,
    SignalType_CalibrationDone
  };
  return values;
}

inline const char * const *EnumNamesSignalType() {
  static const char * const names[8] = {
    "ClientBringup",
    "ClientStateUpdate",
    "INDIGO",
    "INDIGO_TRIAL_TRIGGER",
    "CalibrationNextPose",
    "CalibrationPoseReached",
    "CalibrationDone",
    nullptr
  };
  return names;
}

inline const char *EnumNameSignalType(SignalType e) {
  if (::flatbuffers::IsOutRange(e, SignalType_ClientBringup, SignalType_CalibrationDone)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSignalType()[index];
}

enum ManagerState : int8_t {
  ManagerState_IDLE = 0,
  ManagerState_CONNECT = 1,
  ManagerState_CONNECTED = 2,
  ManagerState_OPENCAMERA = 3,
  ManagerState_CAMERAOPENED = 4,
  ManagerState_ERROR = 5,
  ManagerState_STARTCAMTHREAD = 6,
  ManagerState_THREADREADY = 7,
  ManagerState_RECORDSTOPPED = 8,
  ManagerState_WAITTHREAD = 9,
  ManagerState_WAITSTART = 10,
  ManagerState_WAITSTOP = 11,
  ManagerState_MIN = ManagerState_IDLE,
  ManagerState_MAX = ManagerState_WAITSTOP
};

inline const ManagerState (&EnumValuesManagerState())[12] {
  static const ManagerState values[] = {
    ManagerState_IDLE,
    ManagerState_CONNECT,
    ManagerState_CONNECTED,
    ManagerState_OPENCAMERA,
    ManagerState_CAMERAOPENED,
    ManagerState_ERROR,
    ManagerState_STARTCAMTHREAD,
    ManagerState_THREADREADY,
    ManagerState_RECORDSTOPPED,
    ManagerState_WAITTHREAD,
    ManagerState_WAITSTART,
    ManagerState_WAITSTOP
  };
  return values;
}

inline const char * const *EnumNamesManagerState() {
  static const char * const names[13] = {
    "IDLE",
    "CONNECT",
    "CONNECTED",
    "OPENCAMERA",
    "CAMERAOPENED",
    "ERROR",
    "STARTCAMTHREAD",
    "THREADREADY",
    "RECORDSTOPPED",
    "WAITTHREAD",
    "WAITSTART",
    "WAITSTOP",
    nullptr
  };
  return names;
}

inline const char *EnumNameManagerState(ManagerState e) {
  if (::flatbuffers::IsOutRange(e, ManagerState_IDLE, ManagerState_WAITSTOP)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesManagerState()[index];
}

struct bring_up_message FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef bring_up_messageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SERVER_NAME = 4,
    VT_NUM_CAMERAS = 6
  };
  const ::flatbuffers::String *server_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SERVER_NAME);
  }
  int16_t num_cameras() const {
    return GetField<int16_t>(VT_NUM_CAMERAS, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SERVER_NAME) &&
           verifier.VerifyString(server_name()) &&
           VerifyField<int16_t>(verifier, VT_NUM_CAMERAS, 2) &&
           verifier.EndTable();
  }
};

struct bring_up_messageBuilder {
  typedef bring_up_message Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_server_name(::flatbuffers::Offset<::flatbuffers::String> server_name) {
    fbb_.AddOffset(bring_up_message::VT_SERVER_NAME, server_name);
  }
  void add_num_cameras(int16_t num_cameras) {
    fbb_.AddElement<int16_t>(bring_up_message::VT_NUM_CAMERAS, num_cameras, 0);
  }
  explicit bring_up_messageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<bring_up_message> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<bring_up_message>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<bring_up_message> Createbring_up_message(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> server_name = 0,
    int16_t num_cameras = 0) {
  bring_up_messageBuilder builder_(_fbb);
  builder_.add_server_name(server_name);
  builder_.add_num_cameras(num_cameras);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<bring_up_message> Createbring_up_messageDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *server_name = nullptr,
    int16_t num_cameras = 0) {
  auto server_name__ = server_name ? _fbb.CreateString(server_name) : 0;
  return FetchGame::Createbring_up_message(
      _fbb,
      server_name__,
      num_cameras);
}

struct Server FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ServerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SIGNAL_TYPE = 4,
    VT_CONTROL = 6,
    VT_SERVER_MESG = 8,
    VT_CONFIG_FOLDER = 10,
    VT_RECORD_FOLDER = 12,
    VT_ENCODER_SETUP = 14,
    VT_PTP_GLOBAL_TIME = 16,
    VT_SERVER_STATE = 18,
    VT_FOCUS_VALUE = 20,
    VT_CAMERA_SERIAL = 22,
    VT_IRIS_VALUE = 24
  };
  FetchGame::SignalType signal_type() const {
    return static_cast<FetchGame::SignalType>(GetField<int8_t>(VT_SIGNAL_TYPE, 0));
  }
  FetchGame::ServerControl control() const {
    return static_cast<FetchGame::ServerControl>(GetField<int8_t>(VT_CONTROL, 0));
  }
  const FetchGame::bring_up_message *server_mesg() const {
    return GetPointer<const FetchGame::bring_up_message *>(VT_SERVER_MESG);
  }
  const ::flatbuffers::String *config_folder() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CONFIG_FOLDER);
  }
  const ::flatbuffers::String *record_folder() const {
    return GetPointer<const ::flatbuffers::String *>(VT_RECORD_FOLDER);
  }
  const ::flatbuffers::String *encoder_setup() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ENCODER_SETUP);
  }
  uint64_t ptp_global_time() const {
    return GetField<uint64_t>(VT_PTP_GLOBAL_TIME, 0);
  }
  FetchGame::ManagerState server_state() const {
    return static_cast<FetchGame::ManagerState>(GetField<int8_t>(VT_SERVER_STATE, 0));
  }
  int32_t focus_value() const {
    return GetField<int32_t>(VT_FOCUS_VALUE, 0);
  }
  const ::flatbuffers::String *camera_serial() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CAMERA_SERIAL);
  }
  int32_t iris_value() const {
    return GetField<int32_t>(VT_IRIS_VALUE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_SIGNAL_TYPE, 1) &&
           VerifyField<int8_t>(verifier, VT_CONTROL, 1) &&
           VerifyOffset(verifier, VT_SERVER_MESG) &&
           verifier.VerifyTable(server_mesg()) &&
           VerifyOffset(verifier, VT_CONFIG_FOLDER) &&
           verifier.VerifyString(config_folder()) &&
           VerifyOffset(verifier, VT_RECORD_FOLDER) &&
           verifier.VerifyString(record_folder()) &&
           VerifyOffset(verifier, VT_ENCODER_SETUP) &&
           verifier.VerifyString(encoder_setup()) &&
           VerifyField<uint64_t>(verifier, VT_PTP_GLOBAL_TIME, 8) &&
           VerifyField<int8_t>(verifier, VT_SERVER_STATE, 1) &&
           VerifyField<int32_t>(verifier, VT_FOCUS_VALUE, 4) &&
           VerifyOffset(verifier, VT_CAMERA_SERIAL) &&
           verifier.VerifyString(camera_serial()) &&
           VerifyField<int32_t>(verifier, VT_IRIS_VALUE, 4) &&
           verifier.EndTable();
  }
};

struct ServerBuilder {
  typedef Server Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_signal_type(FetchGame::SignalType signal_type) {
    fbb_.AddElement<int8_t>(Server::VT_SIGNAL_TYPE, static_cast<int8_t>(signal_type), 0);
  }
  void add_control(FetchGame::ServerControl control) {
    fbb_.AddElement<int8_t>(Server::VT_CONTROL, static_cast<int8_t>(control), 0);
  }
  void add_server_mesg(::flatbuffers::Offset<FetchGame::bring_up_message> server_mesg) {
    fbb_.AddOffset(Server::VT_SERVER_MESG, server_mesg);
  }
  void add_config_folder(::flatbuffers::Offset<::flatbuffers::String> config_folder) {
    fbb_.AddOffset(Server::VT_CONFIG_FOLDER, config_folder);
  }
  void add_record_folder(::flatbuffers::Offset<::flatbuffers::String> record_folder) {
    fbb_.AddOffset(Server::VT_RECORD_FOLDER, record_folder);
  }
  void add_encoder_setup(::flatbuffers::Offset<::flatbuffers::String> encoder_setup) {
    fbb_.AddOffset(Server::VT_ENCODER_SETUP, encoder_setup);
  }
  void add_ptp_global_time(uint64_t ptp_global_time) {
    fbb_.AddElement<uint64_t>(Server::VT_PTP_GLOBAL_TIME, ptp_global_time, 0);
  }
  void add_server_state(FetchGame::ManagerState server_state) {
    fbb_.AddElement<int8_t>(Server::VT_SERVER_STATE, static_cast<int8_t>(server_state), 0);
  }
  void add_focus_value(int32_t focus_value) {
    fbb_.AddElement<int32_t>(Server::VT_FOCUS_VALUE, focus_value, 0);
  }
  void add_camera_serial(::flatbuffers::Offset<::flatbuffers::String> camera_serial) {
    fbb_.AddOffset(Server::VT_CAMERA_SERIAL, camera_serial);
  }
  void add_iris_value(int32_t iris_value) {
    fbb_.AddElement<int32_t>(Server::VT_IRIS_VALUE, iris_value, 0);
  }
  explicit ServerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Server> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Server>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Server> CreateServer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    FetchGame::SignalType signal_type = FetchGame::SignalType_ClientBringup,
    FetchGame::ServerControl control = FetchGame::ServerControl_IDLE,
    ::flatbuffers::Offset<FetchGame::bring_up_message> server_mesg = 0,
    ::flatbuffers::Offset<::flatbuffers::String> config_folder = 0,
    ::flatbuffers::Offset<::flatbuffers::String> record_folder = 0,
    ::flatbuffers::Offset<::flatbuffers::String> encoder_setup = 0,
    uint64_t ptp_global_time = 0,
    FetchGame::ManagerState server_state = FetchGame::ManagerState_IDLE,
    int32_t focus_value = 0,
    ::flatbuffers::Offset<::flatbuffers::String> camera_serial = 0,
    int32_t iris_value = 0) {
  ServerBuilder builder_(_fbb);
  builder_.add_ptp_global_time(ptp_global_time);
  builder_.add_iris_value(iris_value);
  builder_.add_camera_serial(camera_serial);
  builder_.add_focus_value(focus_value);
  builder_.add_encoder_setup(encoder_setup);
  builder_.add_record_folder(record_folder);
  builder_.add_config_folder(config_folder);
  builder_.add_server_mesg(server_mesg);
  builder_.add_server_state(server_state);
  builder_.add_control(control);
  builder_.add_signal_type(signal_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Server> CreateServerDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    FetchGame::SignalType signal_type = FetchGame::SignalType_ClientBringup,
    FetchGame::ServerControl control = FetchGame::ServerControl_IDLE,
    ::flatbuffers::Offset<FetchGame::bring_up_message> server_mesg = 0,
    const char *config_folder = nullptr,
    const char *record_folder = nullptr,
    const char *encoder_setup = nullptr,
    uint64_t ptp_global_time = 0,
    FetchGame::ManagerState server_state = FetchGame::ManagerState_IDLE,
    int32_t focus_value = 0,
    const char *camera_serial = nullptr,
    int32_t iris_value = 0) {
  auto config_folder__ = config_folder ? _fbb.CreateString(config_folder) : 0;
  auto record_folder__ = record_folder ? _fbb.CreateString(record_folder) : 0;
  auto encoder_setup__ = encoder_setup ? _fbb.CreateString(encoder_setup) : 0;
  auto camera_serial__ = camera_serial ? _fbb.CreateString(camera_serial) : 0;
  return FetchGame::CreateServer(
      _fbb,
      signal_type,
      control,
      server_mesg,
      config_folder__,
      record_folder__,
      encoder_setup__,
      ptp_global_time,
      server_state,
      focus_value,
      camera_serial__,
      iris_value);
}

inline const FetchGame::Server *GetServer(const void *buf) {
  return ::flatbuffers::GetRoot<FetchGame::Server>(buf);
}

inline const FetchGame::Server *GetSizePrefixedServer(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<FetchGame::Server>(buf);
}

inline bool VerifyServerBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<FetchGame::Server>(nullptr);
}

inline bool VerifySizePrefixedServerBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<FetchGame::Server>(nullptr);
}

inline void FinishServerBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FetchGame::Server> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedServerBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<FetchGame::Server> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace FetchGame

#endif  // FLATBUFFERS_GENERATED_FETCH_FETCHGAME_H_
